version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_db_docker
    restart: always
    
    environment:
      MYSQL_ROOT_PASSWORD: sayaventurespvtltd
      MYSQL_DATABASE: BookMyShowBackend
    
    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: sayaventurespvtltd

    ports:
      - "8081:80"

    depends_on:
      - mysql

  springboot:
    build: .
    container_name: bookMyShow
    restart: always
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: sayaventurespvtltd
      MYSQL_DDL_AUTO: update
      MAIL_USERNAME: yashpurwar.251198@gmail.com
      MAIL_PASSWORD: ptxnrtpuvspdnyor
    ports:
      - "8082:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
